Lots of usability improvements for the I2C API.  Better docs and new top-level functions.
mbed-ce/mbed-os pull request #64
Opened 2022-10-01 07:31 UTC by multiplemonomials

### Summary of changes 

The current Mbed OS I2C API has a number of issues that make it hard for users, especially new users, to program with it effectively.  These include:

- Very inconsistent return codes -- 1 is success from single-byte write() but failure from transaction write()??
- General lack of top-level documentation (what functions do I use for what, what are the gotchas, etc)
- No code examples for async or single-byte APIs
- Confusing information about how repeated starts work
- Lack of information about certain arguments, such as whether addresses need to be ORed with 1, or what happens if you provide both a write buffer and a read buffer to transfer().

This is especially bad because I2C is probably in the top 5 classes that new users will want to interact with.  Are we really OK with giving them this bad of an initial impression??

This PR tries to fix all these issues while maintaining backwards API compatibility.

- Clearly groups the API functions into three groups: transaction-based, single-byte, and asynchronous.  Provides comprehensive top-level documentation about what does what.
- Introduces a new enum, I2C::Result, for return codes.  This enum is compatible with the existing transaction-based API (write() and read()) return codes.
- Clarifies function docs to better state what functions and their arguments do.  For the single-byte API, I made it clear what functions you can legally call next after calling each function.
- Adds new `read_byte()` and `write_byte()` functions which should be used for single-byte reads and writes.  write_byte() uses the same return code as other functions instead of the ad-hoc return code that write(int) uses.  However, I left the old implementations in place for backwards compatibility
- Adds a new `transfer_and_wait()` blocking function for convenience.  This lets you easily have a thread perform blocking I2C operations without messing around with callbacks.  Since the transfer() API is not terribly well-documented or easy to use, this should also serve as an example for how to use it correctly.

Hopefully, all these changes put together should make I2C a lot easier for people to get right!

#### Impact of changes 
Deprecation warnings will be produced for usages of the I2C::write(int) function.

#### Migration actions required 
I2C::write(int) calls will need to be changed to I2C::write_byte() in the long term.  This function uses a different return code enum (I2C::Result), so calling code will need to be modified.

Additionally, code that calls the transaction-based API will should eventually be modified to reference the Result enum.  FOr example,
```cpp
        if (_i2c->write(_i2c_addr | 0, 0, 0) == 0) {
            return 0;
        }
```
should be changed to
```cpp
        if (_i2c->write(_i2c_addr | 0, 0, 0) == I2C::ACK) {
            return 0;
        }
```
This is purely cosmetic though and should not affect functionality.

### Documentation 

Lots of docs in the PR!
----------------------------------------------------------------------------------------------------------------
### Pull request type 

    [] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [] Feature update (New feature / Functionality change / New API)
    [X] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------
### Test results 

    [] No Tests required for this change (E.g docs only update)
    [] Covered by existing mbed-os tests (Greentea or Unittest)
    [] Tests / results supplied as part of this PR
    
Working on testing this as part of my CI test shield.  Stay tuned.
    
----------------------------------------------------------------------------------------------------------------
### Reviewers 

@jay-sridharan 
@JohnK1987 

----------------------------------------------------------------------------------------------------------------

2022-10-01 16:49 UTC, multiplemonomials commented on hal/include/hal/i2c_api.h
> + *  @param address 8-bit address (last bit is 1)
As far as I can tell, this comment is just plain wrong.  The code clearly passes and uses an 8 bit address here.

2022-10-01 22:48 UTC, JohnK1987 requested changes
Just few tips

2022-10-01 22:48 UTC, JohnK1987 commented on drivers/include/drivers/I2C.h
> +     * @param address   8/10 bit %I2C slave address
I don't understand why Arm chose this. Nothing like 8bit address does not exist in I2C spec. It is an address byte what hold 7bit address and 1 bit of direction. In the context of this and the logic of of 8bit address we should call extended version not 10 bit address, but 11bit address or maybe better 16bit address (more exact). So from my point of view 7/10 is correct.

2022-10-01 23:23 UTC, multiplemonomials commented on drivers/include/drivers/I2C.h
> + * All three of these APIs let you execute %I2C operations, but they work differently.
No, this isn't legal code.  In order to do a repeated start, you still have to call start() before the write(data[0]) call.  Do you think the current docs don't make this clear?

2022-10-01 23:25 UTC, multiplemonomials commented on drivers/include/drivers/I2C.h
> +     *  @param address 8-bit I2C slave address [ (7-bit addr << 1) | 1 ]
Looking at the HAL code and the existing docs, it seems really unclear -- there's conflicting information.  I decided to go with the safe interpretation just in case.  If I'm wrong, it shouldn't do any harm.

2022-10-01 23:29 UTC, multiplemonomials commented on drivers/include/drivers/I2C.h
> +     * @param address   8/10 bit %I2C slave address
I just updated the docs to match what the code currently has, didn't want to change the addressing format and break compatibility.  I agree that it's a bit weird that Mbed uses I2C addresses as 8 bit in most contexts, passing around the 7 bit address makes more sense.  Maybe we could try to change that in a future PR.

2022-10-02 08:12 UTC, JohnK1987 commented on drivers/include/drivers/I2C.h
> +     *  @param address 8-bit I2C slave address [ (7-bit addr << 1) | 1 ]
I just wanted to point, that could be unnecessary workaround without real impact.

2022-10-02 09:23 UTC, JohnK1987 commented on drivers/include/drivers/I2C.h
> +     * @param address   8/10 bit %I2C slave address
I didn't mean any significant change, just the description/terminology about the address format.

2022-10-02 17:43 UTC, multiplemonomials commented
@JohnK1987 You're right, I read up a bit on the 10 bit addressing mode and the docs are indeed pretty inconsistent.  Now, most of the HALs don't seem to actually support 10 bit mode natively (certainly not ST's), but it seems like you would generally be working with the address as an 11 bit number, not a 10 bit one, to match how the 8 bit addressing works.  So, I updated instances of "10 bit" to say "11 bit" instead, because I'm pretty sure that's what they actually meant.

Are you good to approve now that this is fixed?

2022-10-02 21:29 UTC, JohnK1987 requested changes

2022-10-02 21:29 UTC, JohnK1987 commented on drivers/include/drivers/I2C.h
> +     *  @param address 8/11-bit I2C slave address [ (7 or 10 bit addr << 1) | 1 ]
Should be 0 I think.

2022-10-02 21:32 UTC, JohnK1987 commented
From my point of view these two links are very handy
* https://en.wikipedia.org/wiki/I%C2%B2C#Addressing_structure
* https://www.totalphase.com/support/articles/200349176-7-bit-8-bit-and-10-bit-I2C-Slave-Addressing
Then It depends what perspective you use for the implementation.

2022-10-02 22:57 UTC, multiplemonomials commented on drivers/include/drivers/I2C.h
> +     *  @param address 8/11-bit I2C slave address [ (7 or 10 bit addr << 1) | 1 ]
Oops, good catch! Fixed

2022-10-03 04:20 UTC, JohnK1987 approved these changes

2022-10-03 04:27 UTC, merged